#!/usr/bin/env node
"use strict";
/* A deployable static site, the installable web app, and a standalone app file. */
const fs = require("node:fs");
const path = require("node:path");
const { createHash } = require("node:crypto");
const { execFileSync } = require("node:child_process");
const ROOT = path.resolve(__dirname, "..");
const WEB = path.join(ROOT, "web");
const SITE = path.join(ROOT, "site");
const OUT = path.join(ROOT, "dist");
function files(dir) {
  return fs.readdirSync(dir, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name)).flatMap(entry => {
    const file = path.join(dir, entry.name);
    if (entry.isSymbolicLink()) throw new Error(`Build input cannot contain symbolic links: ${file}`);
    return entry.isDirectory() ? files(file) : [file];
  });
}
function build() {
  if (!fs.existsSync(path.join(WEB, "index.html"))) throw new Error("web/index.html is missing.");
  execFileSync(process.execPath, [path.join(ROOT, "scripts/build-app-artifact.js")], { cwd: ROOT, stdio: "inherit" });
  const hash = createHash("sha256");
  for (const file of files(WEB)) hash.update(path.relative(WEB, file).replaceAll("\\", "/")).update("\0").update(fs.readFileSync(file));
  const version = hash.digest("hex").slice(0, 16);
  // dist is exclusively generated by this script. Never clean an input path.
  if (path.dirname(OUT) !== ROOT || path.basename(OUT) !== "dist") throw new Error("Invalid build output path");
  if (fs.existsSync(OUT) && fs.lstatSync(OUT).isSymbolicLink()) throw new Error("Refusing to replace a linked dist directory");
  fs.rmSync(OUT, { recursive: true, force: true });
  fs.mkdirSync(OUT, { recursive: true });
  if (fs.existsSync(path.join(SITE, "index.html"))) {
    for (const file of files(SITE)) {
      const relative = path.relative(SITE, file);
      if (relative === "README.md" || relative === "build" || relative.startsWith("build" + path.sep)) continue;
      const dest = path.join(OUT, relative);
      fs.mkdirSync(path.dirname(dest), { recursive: true });
      fs.copyFileSync(file, dest);
    }
    const index = path.join(OUT, "index.html");
    fs.writeFileSync(index, fs.readFileSync(index, "utf8").replaceAll('href="app.html"', 'href="app/"'));
  } else {
    fs.writeFileSync(path.join(OUT, "index.html"), '<!doctype html><meta charset="utf-8"><meta http-equiv="refresh" content="0;url=app/"><title>GRIDLOCK</title><a href="app/">Open GRIDLOCK</a>');
  }
  fs.cpSync(WEB, path.join(OUT, "app"), { recursive: true });
  const worker = path.join(OUT, "app/sw.js");
  if (fs.existsSync(worker)) {
    const before = fs.readFileSync(worker, "utf8");
    const after = before.replace(/const VERSION = ["'][^"']*["'];/, `const VERSION = "gridlock-${version}";`);
    if (before === after) throw new Error("Service worker VERSION declaration was not found.");
    fs.writeFileSync(worker, after);
  }
  fs.copyFileSync(path.join(SITE, "build/app.html"), path.join(OUT, "GRIDLOCK.html"));
  const manifest = { app: "GRIDLOCK Coach", version: require("../package.json").version, contentHash: version, files: {} };
  for (const file of files(OUT)) manifest.files[path.relative(OUT, file).replaceAll("\\", "/")] = createHash("sha256").update(fs.readFileSync(file)).digest("hex");
  fs.writeFileSync(path.join(OUT, "build-manifest.json"), JSON.stringify(manifest, null, 2) + "\n");
  console.log(`Built ${Object.keys(manifest.files).length} files in dist/ (${version}).\nRun npm run preview, or open dist/GRIDLOCK.html directly.`);
  return manifest;
}
if (require.main === module) { try { build(); } catch (error) { console.error(error.message); process.exitCode = 1; } }
module.exports = { build };
