#!/usr/bin/env node
"use strict";
/* A deployable static site, the installable web app, and a standalone app file.
 *
 * With no options this builds the committed source (the default brand) into
 * dist/. scripts/brand.js calls build() with a transformed web/ and site/ and
 * its own output directory to produce a branded copy the same way. */
const fs = require("node:fs");
const path = require("node:path");
const { createHash } = require("node:crypto");
const ROOT = path.resolve(__dirname, "..");
const WEB = path.join(ROOT, "web");
const SITE = path.join(ROOT, "site");
const DIST = path.join(ROOT, "dist");
function files(dir) {
  return fs.readdirSync(dir, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name)).flatMap(entry => {
    const file = path.join(dir, entry.name);
    if (entry.isSymbolicLink()) throw new Error(`Build input cannot contain symbolic links: ${file}`);
    return entry.isDirectory() ? files(file) : [file];
  });
}
function build(opts = {}) {
  const web = opts.web || WEB;
  const site = opts.site || SITE;
  const out = opts.out || DIST;
  const appName = opts.appName || "Gridlock Coach";
  const short = opts.short || appName.replace(/ Coach$/, "");
  const standalone = opts.standalone || `${short.replace(/\s+/g, "")}.html`;
  if (!fs.existsSync(path.join(web, "index.html"))) throw new Error(`${path.relative(ROOT, web)}/index.html is missing.`);
  // The committed build regenerates site/app.html; a branded build brings its
  // own already-bundled app.html inside the site directory it was handed.
  let standaloneSource;
  if (opts.site) {
    standaloneSource = path.join(site, "app.html");
    if (!fs.existsSync(standaloneSource)) throw new Error("The branded site copy has no app.html; bundle it before building.");
  } else {
    const { bundle } = require("./build-app-artifact");
    const html = bundle(web);
    for (const rel of ["site/app.html", "site/build/app.html"]) {
      const file = path.join(ROOT, rel);
      fs.mkdirSync(path.dirname(file), { recursive: true });
      fs.writeFileSync(file, html);
      console.log(`${rel}: ${(Buffer.byteLength(html) / 1024).toFixed(0)} KB`);
    }
    standaloneSource = path.join(SITE, "build/app.html");
  }
  const hash = createHash("sha256");
  for (const file of files(web)) hash.update(path.relative(web, file).replaceAll("\\", "/")).update("\0").update(fs.readFileSync(file));
  const version = hash.digest("hex").slice(0, 16);
  // dist is exclusively generated by this script. Never clean an input path.
  const resolved = path.resolve(out);
  if (resolved !== DIST && !resolved.startsWith(DIST + path.sep)) throw new Error("Invalid build output path");
  if (fs.existsSync(resolved) && fs.lstatSync(resolved).isSymbolicLink()) throw new Error("Refusing to replace a linked dist directory");
  fs.rmSync(resolved, { recursive: true, force: true });
  fs.mkdirSync(resolved, { recursive: true });
  if (fs.existsSync(path.join(site, "index.html"))) {
    for (const file of files(site)) {
      const relative = path.relative(site, file);
      if (relative === "README.md" || relative === "build" || relative.startsWith("build" + path.sep)) continue;
      // Another brand's contact file describes another build; it never ships in this one.
      if (/^contact\.[a-z0-9]+\.json$/.test(relative)) continue;
      const dest = path.join(resolved, relative);
      fs.mkdirSync(path.dirname(dest), { recursive: true });
      fs.copyFileSync(file, dest);
    }
    const index = path.join(resolved, "index.html");
    fs.writeFileSync(index, fs.readFileSync(index, "utf8").replaceAll('href="app.html"', 'href="app/"'));
  } else {
    fs.writeFileSync(path.join(resolved, "index.html"), `<!doctype html><meta charset="utf-8"><meta http-equiv="refresh" content="0;url=app/"><title>${short}</title><a href="app/">Open ${short}</a>`);
  }
  fs.cpSync(web, path.join(resolved, "app"), { recursive: true });
  const worker = path.join(resolved, "app/sw.js");
  if (fs.existsSync(worker)) {
    const before = fs.readFileSync(worker, "utf8");
    // "gridlock-" is the cache namespace, not the brand: it stays the same in every build.
    const after = before.replace(/const VERSION = ["'][^"']*["'];/, `const VERSION = "gridlock-${version}";`);
    if (before === after) throw new Error("Service worker VERSION declaration was not found.");
    fs.writeFileSync(worker, after);
  }
  fs.copyFileSync(standaloneSource, path.join(resolved, standalone));
  const manifest = { app: appName, version: require("../package.json").version, contentHash: version, files: {} };
  if (opts.brand) manifest.brand = opts.brand;
  for (const file of files(resolved)) manifest.files[path.relative(resolved, file).replaceAll("\\", "/")] = createHash("sha256").update(fs.readFileSync(file)).digest("hex");
  fs.writeFileSync(path.join(resolved, "build-manifest.json"), JSON.stringify(manifest, null, 2) + "\n");
  const shown = path.relative(ROOT, resolved) || "dist";
  console.log(`Built ${Object.keys(manifest.files).length} files in ${shown}/ (${version}).\nRun npm run preview, or open ${shown}/${standalone} directly.`);
  return manifest;
}
if (require.main === module) { try { build(); } catch (error) { console.error(error.message); process.exitCode = 1; } }
module.exports = { build, files };
