#!/usr/bin/env node
"use strict";
/* The cloud build — the ONE build that turns League sync on.
 *
 * It copies the web app verbatim, drops in the reference adapter
 * (native/gridlock-cloud.js) and a generated gridlock-config.js naming your
 * Supabase project, and wires both into index.html BEFORE the app boots, so
 * window.gridlockCloud is present on the first render and the sign-in copy is
 * already truthful. The committed web/ is never touched — it stays fetch-free —
 * so the default and offline builds are exactly as before.
 *
 *   GRINDX_SUPABASE_URL=https://YOUR.supabase.co \
 *   GRINDX_SUPABASE_ANON_KEY=eyJ... \
 *   npm run build:cloud
 *
 * Output: dist/cloud/ — point the Capacitor webDir at it for a native cloud
 * build, or serve it as the web cloud build. The anon key is public by design;
 * the service key never appears here.
 */
const fs = require("node:fs");
const path = require("node:path");

const ROOT = path.resolve(__dirname, "..");
const WEB = path.join(ROOT, "web");
const ADAPTER = path.join(ROOT, "native", "gridlock-cloud.js");
const ANCHOR = '<script src="voice.js"></script>';   // the last lib before the inline app

function build({ url, anonKey, outDir } = {}) {
  if (!url || !anonKey) {
    throw new Error("Set GRINDX_SUPABASE_URL and GRINDX_SUPABASE_ANON_KEY (the anon / public key, never the service key).");
  }
  if (!/^https:\/\/[^\s/]+/.test(url)) throw new Error("GRINDX_SUPABASE_URL must be an https:// URL.");
  if (/service_role|service-role/i.test(anonKey)) throw new Error("That looks like a service key. Use the anon (public) key — the service key must never ship.");

  outDir = outDir || path.join(ROOT, "dist", "cloud");
  fs.rmSync(outDir, { recursive: true, force: true });
  fs.mkdirSync(outDir, { recursive: true });

  // The web app, verbatim.
  fs.cpSync(WEB, outDir, { recursive: true });

  // The adapter, and the config that names the project.
  fs.copyFileSync(ADAPTER, path.join(outDir, "gridlock-cloud.js"));
  fs.writeFileSync(path.join(outDir, "gridlock-config.js"),
    "/* Generated by scripts/cloud-build.js — do not edit; re-run the build. */\n" +
    "window.GRIDLOCK_CLOUD = " + JSON.stringify({ url: url.replace(/\/+$/, ""), anonKey }) + ";\n");

  // Wire them in, config first, before the app boots.
  const idx = path.join(outDir, "index.html");
  let html = fs.readFileSync(idx, "utf8");
  if (!html.includes(ANCHOR)) throw new Error("Could not find the injection anchor in index.html; the build layout changed.");
  if (html.includes("gridlock-config.js")) throw new Error("index.html already references the cloud config — refusing to double-inject.");
  html = html.replace(ANCHOR, ANCHOR + '\n<script src="gridlock-config.js"></script>\n<script src="gridlock-cloud.js"></script>');
  fs.writeFileSync(idx, html);

  return { outDir, host: url.replace(/\/+$/, "") };
}

module.exports = { build };

if (require.main === module) {
  try {
    const r = build({ url: process.env.GRINDX_SUPABASE_URL, anonKey: process.env.GRINDX_SUPABASE_ANON_KEY });
    console.log(`Cloud build → ${path.relative(ROOT, r.outDir)}/  (project ${r.host})`);
    console.log("Point Capacitor's webDir at it (or serve it) for a build with League sync on.");
  } catch (e) {
    console.error(e.message);
    process.exitCode = 1;
  }
}
